package com.db.jdbc.conn.entities;

import java.util.Date;

public class Comment {
	
	private int id;							//Will be autogenerated by database
	private String comment;
	private Date commentDate;
	private Movie movie;
	private User user;
	
	public Comment() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param id
	 * @param comment
	 * @param commentDate
	 * @param movie
	 * @param user
	 */
	public Comment(int id, String comment, Date commentDate, Movie movie,
			User user) {
		super();
		this.id = id;
		this.comment = comment;
		this.commentDate = commentDate;
		this.movie = movie;
		this.user = user;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCommentDate() {
		return commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	public Movie getMovie() {
		return movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}
